### ISSUE TITLE
[--rate_limit] A stable relative error (~7.5%) observed

### ISSUE THREAD

**Issue by doctormin** [linux-rdma/perftest#125] opened 2021-09-06 06:20 UTC
Hi all:

I'm very interested in your work. And I personally tested `--rate_limit` using a Python script between two machines in an IB network. The network traffic limits were set ranging from 10MBps to 5000MBps+. Whether it is `ib_send_bw`,`ib_read_bw` or `ib_write_bw`,  a stable relative error was observed.
**The rate_limit_type is SW.**:
![image](https://user-images.githubusercontent.com/49093593/132168976-ea952fab-7c0f-420f-b7d4-ec350db2043d.png)
I wonder what mechanism causes this stable relative error， thanks!

**Comment by doctormin** [comment] 2021-09-06 10:23
<img src="https://render.githubusercontent.com/render/math?math=relative\_error = \frac{|rate\_limit - actual\_rate|}{rate\_limit}">

**Comment by HassanKhadour** [comment] 2022-11-10 11:47
Hi doctormin, thanks for the info!
Can you please help on how to reproduce it ?

**Comment by doctormin** [comment] 2022-11-10 12:10
Hi Hassan! I am afraid that I can not share the .py script immediately because this test was done by me when I was working for an enterprise (I don't have access to it any more). But I can explain more about what happened in my test script:
- In a for loop, the input to `--rate_limit` was set in range(5, 5750, 5)
    - then  the "actual rate achieved" was got from the terminal output of perftest everytime it finished.

So the script can collect multiple `<input: rate_limit>, <output: actual_rate>` data pairs. That's how I draw the diagram above.

This relative error was stable and reproducible in my experience when I was working on it. Could it be that **the input (args --rate_limit) is throughput and the output of perftest's terminal report is goodput**?

**Comment by HassanKhadour** [comment] 2022-11-10 12:52
Hi, perftest output is goodput, I'm trying to reproduce this issue but I can't get those relative errors, I can get barely 1.5%~ at maximum

**Comment by doctormin** [comment] 2022-11-10 13:23
I see, thanks for the information. Maybe the packet size setting will influence the gap between throughput and good put (but I am not so sure). In my previous test (~7.5% result), I select the very packet size which can make the throughput to be MAX in my testbed (by carrying out `-a` test first), but I didn't remember the exact value of it.

**Comment by HassanKhadour** [comment] 2022-12-01 13:08
Hi @doctormin, We investigated the Issue and soon a fix will be merged.
The problem is in some formula we were dividing integers and therefore the fractions were ignored, now we changed the types of those variables to be "double".
After the Fix the results will be much more accurate.

**Comment by doctormin** [comment] 2022-12-02 18:01
Happy to hear about that :)
Thank you guys for a great job

**Comment by HassanKhadour** [comment] 2022-12-07 12:19
Our pleasure!
Please check it if you can
https://github.com/linux-rdma/perftest/commit/1ef49c4c3c63b25b61a8eda9c3065f6a5f386aee

**Comment by HassanKhadour** [comment] 2022-12-19 13:28
Hi @doctormin,
Can you please update us if u checked it?

**Comment by doctormin** [comment] 2022-12-19 15:20
Hi Hassan,
I am sorry that I can not check this issue in near future.
Because this issue was discovered when I was an intern in an HPC-related enterprise, and currently I don't have access for an IB cluster any more.

**Comment by HassanKhadour** [comment] 2022-12-21 09:51
No worries, thanks for reporting the Issue, Closing

**Closed by HassanKhadour** 2022-12-21 09:51 UTC
