### ISSUE TITLE
Negative value of BW average and t_avg observevd

### ISSUE THREAD

**Issue by sunmingbao** [linux-rdma/perftest#82] opened 2020-04-02 09:41 UTC
**Version used**
lehi-smoke:~ # ib_send_lat  --version
Version: 5.60
lehi-smoke:~ # ib_send_bw  --version
Version: 5.60
lehi-smoke:~ # 

**Test Method**
4 hosts with MLX HCA inter-connected with ethernet switches.
Each host launches 12 server processes (3 ib_send_bw, 3 ib_write_bw, 3 ib_send_lat, 3 ib_write_lat).
Each host launches 12 client processes (3 ib_send_bw, 3 ib_write_bw, 3 ib_send_lat, 3 ib_write_lat).
It was a full-cross test, each host act as both server and client for other 3 hosts.
And no rate limitation was used.

**Problem**
Negative value observed in the log of some bw or lat process.
Following is some of the logs.

Fri, 20 Mar 2020 22:35:36 +0800

+ taskset -c 17 ib_send_bw -d mlx5_bond_0 -z -f 2 -F --report_gbits -D 205200 -p 20003 -x 3 192.168.219.6
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF		Device         : mlx5_bond_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 1
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 0[B]
 rdma_cm QPs	 : OFF
 Data ex. method : rdma_cm
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x1295 PSN 0xe41d73
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:05
 remote address: LID 0000 QPN 0x126e PSN 0x9f23a6
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:06
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
 65536      18446744072490473291           0.000000            -3.122397            -0.005955
---------------------------------------------------------------------------------------
Mon, 23 Mar 2020 07:35:37 +0800

Fri, 20 Mar 2020 22:34:20 +0800

+ taskset -c 1 ib_send_bw -d mlx5_bond_0 -z -f 2 -F --report_gbits -D 205200 -p 20001 -x 3

************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF		Device         : mlx5_bond_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 RX depth        : 512
 CQ Moderation   : 1
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 0[B]
 rdma_cm QPs	 : OFF
 Data ex. method : rdma_cm
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x12a1 PSN 0x2955ce
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:05
 remote address: LID 0000 QPN 0x127e PSN 0x2afc3c
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:06
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
 65536      1906054058       0.00               4.88   		   0.009312
---------------------------------------------------------------------------------------
Mon, 23 Mar 2020 07:35:47 +0800

Fri, 20 Mar 2020 22:34:20 +0800

+ taskset -c 7 ib_send_lat -d mlx5_bond_0 -z -f 2 -F --report_gbits -D 205200 -p 40001 -x 3

************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF		Device         : mlx5_bond_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 RX depth        : 512
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 236[B]
 rdma_cm QPs	 : OFF
 Data ex. method : rdma_cm
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x12a4 PSN 0xb2115c
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:05
 remote address: LID 0000 QPN 0x1280 PSN 0x6966f2
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:06
---------------------------------------------------------------------------------------
 #bytes        #iterations       t_avg[usec]    tps average
 2             -267885825            -382.06        -1308.69
---------------------------------------------------------------------------------------
Mon, 23 Mar 2020 07:35:48 +0800

Fri, 20 Mar 2020 22:34:20 +0800

+ taskset -c 8 ib_send_lat -d mlx5_bond_0 -z -f 2 -F --report_gbits -D 205200 -p 40002 -x 3

************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF		Device         : mlx5_bond_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 RX depth        : 512
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 236[B]
 rdma_cm QPs	 : OFF
 Data ex. method : rdma_cm
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x12ac PSN 0xc7fee4
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:05
 remote address: LID 0000 QPN 0x128b PSN 0x57659e
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:219:07
---------------------------------------------------------------------------------------
 #bytes        #iterations       t_avg[usec]    tps average
 2             1158940729            88.31          5661.71
---------------------------------------------------------------------------------------
Mon, 23 Mar 2020 07:35:57 +0800

**Comment by HassanKhadour** [comment] 2022-11-10 11:13
Hi,
Its hard to repro since must run it for a long period of time.
I guess its overflow in some variable resulted by running the test for such a long time.
Does it repro with less duration?

**Comment by HassanKhadour** [comment] 2022-12-21 09:53
Closing the Issue, Please reopen if reproduce

**Closed by HassanKhadour** 2022-12-21 09:53 UTC
