### ISSUE TITLE
ib_send_bw test stuck

### ISSUE THREAD

**Issue by amitgeron** [linux-rdma/perftest#137] opened 2022-02-02 14:00 UTC
When running the following, for example:
ib_send_bw -b -e -q 16

I think that the root cause is wrong usage of notifications - the cq isn't emptied when the application is woken up. The argument passed to ibv_poll_cq is user_param->rx_depth, but we might have more completions than that, since we use multiple QPs.

There are two options I can think of for a fix:

1. Use a larger completion buffer when calling ibv_poll_cq (user_param->rx_depth * number_of_qps)
2. As done in run_iter_be_server - loop over ibv_poll_cq as long as there are completions in the cq

**Comment by sshaulnv** [comment] 2022-07-13 12:20
Hi,
The issue is not reproducing on my setup.
can you please provide more information about your setup and chip , driver, etc?
Thanks

**Comment by HassanKhadour** [comment] 2022-11-10 11:03
Hi amitgeron,
Thanks for your collaboration!
as you said there is a linked PR for this issue that is waiting for code fix, So I'll close this issue

**Closed by HassanKhadour** 2022-11-10 11:03 UTC
